apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: acloud-simple-ui
spec:
  hosts:
  - "*"
  gateways:
  - acloud-simple-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: acloud-simple-ui
